# Generated by Django 4.2.13 on 2026-02-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_profile_cosmos_gold_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, help_text='User balance after withdrawal', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, help_text='User balance before withdrawal', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet_metamask_bsc',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
