# Generated by Django 4.2.13 on 2026-02-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_withdrawalrequest_balance_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='miners/')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20)),
                ('attempts', models.PositiveIntegerField(help_text='Cantidad de intentos de minado por viaje')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Disponible'), ('traveling', 'Viajando')], default='idle', max_length=20)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('miner_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_miners', to='game.minertype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miners', to='game.profile')),
            ],
        ),
    ]
