# Generated by Django 4.2.13 on 2026-02-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_minertype_userminer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transports/')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Cantidad máxima de recursos que puede transportar')),
                ('speed', models.PositiveIntegerField(help_text='Velocidad del transporte (impacta tiempo de viaje)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Disponible'), ('traveling', 'En viaje')], default='idle', max_length=20)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='game.profile')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_transports', to='game.transporttype')),
            ],
        ),
    ]
