# Generated by Django 4.2.13 on 2026-02-04 04:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_minertype_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tools/')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20)),
                ('production_multiplier', models.DecimalField(decimal_places=2, help_text='Multiplicador de producción. Ej: 1.20 = +20%', max_digits=5)),
                ('success_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus adicional de probabilidad de éxito (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Disponible'), ('traveling', 'En uso')], default='idle', max_length=20)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='game.profile')),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tools', to='game.tooltype')),
            ],
        ),
    ]
