# Generated by Django 4.2.13 on 2026-03-15 14:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_tooltype_usertool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Imagen o GIF del cofre', upload_to='chests/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_in_store', models.BooleanField(default=True, verbose_name='¿Aparece en tienda?')),
                ('rewards_per_open', models.PositiveIntegerField(default=1, help_text='Número de recompensas por cada apertura de cofre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cofre',
                'verbose_name_plural': 'Cofres',
            },
        ),
        migrations.CreateModel(
            name='ChestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Cofre',
                'verbose_name_plural': 'Categorías de Cofres',
            },
        ),
        migrations.CreateModel(
            name='ChestReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_probability', models.DecimalField(decimal_places=2, help_text='Lo que se muestra al usuario (ej: 10.50)', max_digits=5, verbose_name='Probabilidad Usuario (%)')),
                ('code_probability', models.DecimalField(decimal_places=4, help_text='Valor decimal real (ej: 0.1050). La suma de esto en un cofre debe ser 1.', max_digits=5, verbose_name='Probabilidad Código')),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.chest')),
                ('miner_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chest_rewards', to='game.minertype')),
                ('tool_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chest_rewards', to='game.tooltype')),
                ('transport_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chest_rewards', to='game.transporttype')),
            ],
            options={
                'verbose_name': 'Recompensa de Cofre',
                'verbose_name_plural': 'Recompensas de Cofres',
            },
        ),
        migrations.AddField(
            model_name='chest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chests', to='game.chestcategory'),
        ),
    ]
