# Generated by Django 4.2.13 on 2026-03-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_chest_chestcategory_chestreward_chest_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_chests', to='game.profile')),
            ],
            options={
                'verbose_name': 'Cofre de Usuario',
                'verbose_name_plural': 'Cofres de Usuarios',
            },
        ),
    ]
