# Generated by Django 4.2.13 on 2026-03-16 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('min_miner_attempts', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mín. Intentos Minero')),
                ('min_transport_speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mín. Velocidad Transporte')),
                ('min_tool_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mín. Multiplicador Herramienta')),
                ('lock_duration_days', models.PositiveIntegerField(default=7, verbose_name='Días de Inhabilitación de items')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='game.season')),
            ],
            options={
                'verbose_name': 'Nivel de Temporada',
                'verbose_name_plural': 'Niveles de Temporada',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSeasonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('locked_until', models.DateTimeField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.seasonlevel')),
                ('miner_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.userminer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.season')),
                ('tool_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.usertool')),
                ('transport_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.usertransport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada a Temporada',
                'verbose_name_plural': 'Entradas a Temporada',
                'unique_together': {('user', 'season')},
            },
        ),
    ]
