# Generated by Django 4.2.13 on 2026-03-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_seasonlevel_userseasonentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonlevel',
            name='min_miner_attempts',
        ),
        migrations.RemoveField(
            model_name='seasonlevel',
            name='min_tool_multiplier',
        ),
        migrations.RemoveField(
            model_name='seasonlevel',
            name='min_transport_speed',
        ),
        migrations.CreateModel(
            name='SeasonLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('miner_attempts', 'Mín. Intentos Minero'), ('transport_speed', 'Mín. Velocidad (Transporte)'), ('tool_multiplier', 'Mín. Multiplicador (Herramienta)')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='game.seasonlevel')),
            ],
        ),
    ]
