# Generated by Django 4.2.13 on 2026-03-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_seasonlevel_min_miner_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonLevelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('gold', 'Cosmogold / Moneda'), ('miner', 'Minero Especial'), ('transport', 'Transporte Especial'), ('tool', 'Herramienta Especial')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad / Oro')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.seasonlevel')),
                ('miner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.minertype')),
                ('tool_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tooltype')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.transporttype')),
            ],
        ),
    ]
