# Generated by Django 4.2.13 on 2026-03-17 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0013_seasonlevelreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='minerals/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='planets/')),
                ('travel_time_base', models.PositiveIntegerField(help_text='Tiempo base en horas')),
                ('success_rate_base', models.PositiveIntegerField(help_text='Porcentaje de éxito base (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField()),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mineral')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produced_minerals', to='game.planet')),
            ],
        ),
        migrations.CreateModel(
            name='MiningTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField()),
                ('success_rate', models.PositiveIntegerField()),
                ('production_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('results_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ongoing', 'En viaje'), ('finished', 'Terminado'), ('collected', 'Recolectado')], default='ongoing', max_length=20)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.userminer')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.planet')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.usertool')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.usertransport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mineral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_minerals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mineral')},
            },
        ),
    ]
