# Generated by Django 4.2.13 on 2026-03-17 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_mineral_planet_planetmineral_miningtrip_usermineral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooltype',
            name='production_multiplier',
        ),
        migrations.RemoveField(
            model_name='tooltype',
            name='success_bonus',
        ),
        migrations.AddField(
            model_name='tooltype',
            name='bonus_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Bonus de producción en %. Ej: 100=x1, 200=x2 (duplica rango mineral)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='seasonlevelrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('miner_attempts', 'Mín. Intentos Minero'), ('transport_speed', 'Mín. Velocidad (Transporte)'), ('tool_bonus', 'Mín. Bonus % (Herramienta)')], max_length=50),
        ),
    ]
