# Generated by Django 4.2.13 on 2026-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_tooltype_production_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='puntos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos máximos ganados por viaje exitoso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
