# Generated by Django 4.2.13 on 2026-03-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_planet_puntos_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseasonentry',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Puntos Acumulados'),
        ),
    ]
