# Generated by Django 4.2.13 on 2026-03-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_userseasonentry_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonlevelreward',
            name='mineral_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral'),
        ),
        migrations.AddField(
            model_name='seasonlevelreward',
            name='rank_end',
            field=models.PositiveIntegerField(default=1, verbose_name='Puesto Fin'),
        ),
        migrations.AddField(
            model_name='seasonlevelreward',
            name='rank_start',
            field=models.PositiveIntegerField(default=1, verbose_name='Puesto Inicio'),
        ),
        migrations.AlterField(
            model_name='seasonlevelreward',
            name='reward_type',
            field=models.CharField(choices=[('gold', 'Cosmogold / Moneda'), ('miner', 'Minero Especial'), ('transport', 'Transporte Especial'), ('tool', 'Herramienta Especial'), ('mineral', 'Mineral')], max_length=20),
        ),
    ]
