# Generated by Django 4.2.13 on 2026-03-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_seasonlevelreward_mineral_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseasonentry',
            name='rewards_claimed',
            field=models.BooleanField(default=False, verbose_name='Recompensas Reclamadas'),
        ),
    ]
