# Generated by Django 4.2.13 on 2026-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_userseasonentry_rewards_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='minertype',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tooltype',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
