# Generated by Django 4.2.13 on 2026-03-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_minertype_is_free_planet_is_free_tooltype_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporttype',
            name='capacity',
        ),
    ]
