# Generated by Django 4.2.13 on 2026-03-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_remove_transporttype_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('miner', 'Minero'), ('transport', 'Transporte'), ('tool', 'Herramienta'), ('gold', 'Cosmos Gold')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Para Gold o cantidad', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.minertype')),
                ('tool_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tooltype')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.transporttype')),
            ],
        ),
    ]
