# Generated by Django 4.2.13 on 2026-03-20 18:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_registrationreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='minertype',
            name='points_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplicador de puntos de planeta. 1=normal, 2=doble, etc.', max_digits=5),
        ),
        migrations.AddField(
            model_name='minertype',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Temporada a la que aplica el multiplicador de puntos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miner_types', to='game.season'),
        ),
        migrations.AlterField(
            model_name='minertype',
            name='rarity',
            field=models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='rarity',
            field=models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='rarity',
            field=models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20),
        ),
    ]
