# Generated by Django 4.2.13 on 2026-03-21 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_add_points_multiplier_season_to_minertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='gold_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Equivalencia en Cosmos Gold para 1 unidad de este mineral', max_digits=12),
        ),
    ]
