# Generated by Django 4.2.13 on 2026-03-21 12:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_mineral_gold_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilCentralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='oil_centrals/')),
                ('price_gold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_life_days', models.PositiveIntegerField(default=10)),
                ('max_life_days', models.PositiveIntegerField(default=30)),
                ('min_barrels_24h', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('max_barrels_24h', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('min_refined_24h', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_refined_24h', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOilCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_life_days', models.IntegerField()),
                ('barrels_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refined_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('last_collection', models.DateTimeField(auto_now_add=True)),
                ('central_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.oilcentraltype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_centrals', to='game.profile')),
            ],
        ),
    ]
