# Generated by Django 4.2.13 on 2026-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_oilcentraltype_useroilcentral'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroilcentral',
            name='initial_life_days',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
