# Generated by Django 4.2.13 on 2026-03-24 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_useroilcentral_initial_life_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcentraltype',
            name='refined_mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral'),
        ),
        migrations.AddField(
            model_name='oilcentraltype',
            name='refined_mineral_qty',
            field=models.PositiveIntegerField(default=1, help_text='Amount of mineral given after refining'),
        ),
        migrations.AddField(
            model_name='oilcentraltype',
            name='refining_cooldown_hours',
            field=models.PositiveIntegerField(default=360, help_text='Default 15 days (360h)'),
        ),
        migrations.AddField(
            model_name='useroilcentral',
            name='refining_charges',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='useroilcentral',
            name='refining_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useroilcentral',
            name='refining_status',
            field=models.CharField(choices=[('idle', 'Inactivo'), ('refining', 'Refinando'), ('ready', 'Listo para reclamar')], default='idle', max_length=20),
        ),
    ]
