# Generated by Django 4.2.13 on 2026-03-24 01:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_oilcentraltype_refined_mineral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='purchase_mineral',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona un mineral, este cofre se comprará con ese mineral en lugar de Cosmos Gold.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral'),
        ),
        migrations.AddField(
            model_name='chest',
            name='purchase_mineral_qty',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de mineral extra necesario.'),
        ),
        migrations.AlterField(
            model_name='chest',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en Cosmos Gold (si no hay mineral seleccionado)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
