# Generated by Django 4.2.13 on 2026-03-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_chest_purchase_mineral_chest_purchase_mineral_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilcentraltype',
            name='purchase_mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_purchase', to='game.mineral'),
        ),
        migrations.AddField(
            model_name='oilcentraltype',
            name='purchase_mineral_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
