# Generated by Django 4.2.13 on 2026-03-24 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0029_oilcentraltype_purchase_mineral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral_qty', models.PositiveIntegerField(help_text='Cantidad de mineral requerida')),
                ('gold_reward', models.DecimalField(decimal_places=2, help_text='Recompensa en Cosmos Gold', max_digits=12)),
                ('duration_hours', models.PositiveIntegerField(default=360, help_text='Duración en horas (ej: 360 para 15 días)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='game.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='UserActiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tradeoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
