# Generated by Django 4.2.13 on 2026-03-24 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_tradeoffer_useractivetrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packs/', verbose_name='Imagen')),
                ('price_gold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio en GOLD')),
                ('purchase_mineral_qty', models.IntegerField(default=0, verbose_name='Cantidad de mineral requerida')),
                ('external_link', models.URLField(blank=True, help_text='Si se llena, el botón de compra abrirá este enlace. No se cobrará GOLD ni mineral.', max_length=500, null=True, verbose_name='Link Externo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_mineral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral', verbose_name='Mineral de compra alternativo')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='PackToolReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=4, help_text='Probabilidad real entre 0 y 1. La suma del pack debe ser 1.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('probability_label', models.CharField(help_text="Texto visible para el usuario. Ej: 'Común', '30%'", max_length=50)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_rewards', to='game.storepack')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tooltype', verbose_name='Tipo de Herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='PackMinerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=4, help_text='Probabilidad real entre 0 y 1 (ej: 0.15 = 15%). La suma del pack debe ser 1.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('probability_label', models.CharField(help_text="Texto visible para el usuario. Ej: 'Alta', '15%', 'Muy Rara'", max_length=50)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.minertype', verbose_name='Tipo de Minero')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miner_rewards', to='game.storepack')),
            ],
        ),
    ]
