# Generated by Django 4.2.13 on 2026-03-24 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_storepack_packtoolreward_packminerreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackTransportReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=4, help_text='Probabilidad real entre 0 y 1. La suma del pack debe ser 1.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('probability_label', models.CharField(help_text="Texto visible para el usuario. Ej: 'Épico', '5%'", max_length=50)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_rewards', to='game.storepack')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.transporttype', verbose_name='Tipo de Transporte')),
            ],
        ),
    ]
