# Generated by Django 4.2.13 on 2026-03-24 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0032_packtransportreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blessings/')),
                ('price_gold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_mineral_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Horas antes de poder reclamar de nuevo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_mineral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='StaticBlessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('oil', 'Bendición del Petróleo'), ('vip', 'Bendición VIP'), ('cosmos', 'Bendición Cosmos'), ('extra', 'Bendición Extra')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje visual (ej: 1.00 para 1%)', max_digits=5)),
                ('required_pack', models.ForeignKey(blank=True, help_text='Pack requerido para la bendición Cosmos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.storepack')),
            ],
        ),
        migrations.CreateModel(
            name='UserBlessingClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('blessing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.blessing')),
                ('static_blessing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.staticblessing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blessings_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'blessing'], name='game_userbl_user_id_5acd35_idx'), models.Index(fields=['user', 'static_blessing'], name='game_userbl_user_id_735b3d_idx')],
            },
        ),
    ]
