# Generated by Django 4.2.13 on 2026-03-24 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0033_blessing_staticblessing_userblessingclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.storepack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
