# Generated by Django 4.2.13 on 2026-03-24 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_packpurchaselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackBlessingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=4, help_text='Probabilidad real entre 0 y 1. La suma del pack debe ser 1.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('probability_label', models.CharField(help_text="Texto visible para el usuario. Ej: 'Gesto de Suerte', '1%'", max_length=50)),
                ('blessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.blessing', verbose_name='Bendición Dinámica')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blessing_rewards', to='game.storepack')),
            ],
        ),
    ]
