# Generated by Django 4.2.13 on 2026-03-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0035_packblessingreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessing',
            name='reward_mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.mineral'),
        ),
        migrations.AddField(
            model_name='blessing',
            name='reward_mineral_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='price_mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.mineral'),
        ),
        migrations.CreateModel(
            name='UserDynamicBlessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('last_claim_at', models.DateTimeField(blank=True, null=True)),
                ('blessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.blessing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_dynamic_blessings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'blessing')},
            },
        ),
    ]
