# Generated by Django 4.2.13 on 2026-03-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_blessing_reward_mineral_blessing_reward_mineral_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessing',
            name='reward_gold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
