# Generated by Django 4.2.13 on 2026-03-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alliance_profile_alliance_cooldown_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_max_members', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
