# Generated by Django 4.2.13 on 2026-03-27 03:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_allianceglobalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='is_alliance',
            field=models.BooleanField(default=False, help_text='¿Es un planeta exclusivo de alianzas?'),
        ),
        migrations.AddField(
            model_name='planet',
            name='price_gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio en Cosmos Gold', max_digits=12),
        ),
        migrations.CreateModel(
            name='AlliancePlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_planets', to='game.alliance')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.planet')),
            ],
            options={
                'unique_together': {('alliance', 'planet')},
            },
        ),
    ]
