# Generated by Django 4.2.13 on 2026-03-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_planet_is_alliance_planet_price_gold_allianceplanet'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='price_mineral',
            field=models.ForeignKey(blank=True, help_text='Mineral especial para adquirir planeta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral'),
        ),
        migrations.AddField(
            model_name='planet',
            name='price_mineral_quantity',
            field=models.FloatField(default=0, help_text='Cantidad del mineral especial'),
        ),
    ]
