# Generated by Django 4.2.13 on 2026-03-29 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0041_planet_price_mineral_planet_price_mineral_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of_alliance', to=settings.AUTH_USER_MODEL),
        ),
    ]
