# Generated by Django 4.2.13 on 2026-03-29 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0042_alliance_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alliance_gifts/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('gold_amount', models.PositiveIntegerField(default=0, help_text='Cosmos Gold a entregar')),
                ('mineral_quantity', models.PositiveIntegerField(default=0, help_text='Cantidad del mineral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miner_type', models.ForeignKey(blank=True, help_text='Tipo de minero a entregar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.minertype')),
                ('mineral', models.ForeignKey(blank=True, help_text='Mineral a entregar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mineral')),
                ('tool_type', models.ForeignKey(blank=True, help_text='Tipo de herramienta a entregar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tooltype')),
                ('transport_type', models.ForeignKey(blank=True, help_text='Tipo de transporte a entregar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceGiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_raffled', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_assignments', to='game.alliance')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='game.alliancegift')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceGiftWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_record', to='game.alliancegiftassignment')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
