# Generated by Django 4.2.13 on 2026-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_alliancegift_alliancegiftassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancegiftwinner',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
