# Generated by Django 4.2.13 on 2026-03-31 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0044_alliancegiftwinner_is_claimed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarketExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mineral', models.PositiveIntegerField()),
                ('gold_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mineral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_multiplier', models.DecimalField(decimal_places=2, help_text='Relación: 1 unidad de mineral = X Cosmos Gold', max_digits=12)),
                ('exchange_duration_hours', models.PositiveIntegerField(default=24, help_text='Tiempo en horas que tarda en procesarse el intercambio')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mineral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_config', to='game.mineral')),
            ],
        ),
    ]
