# Generated by Django 4.2.13 on 2026-03-31 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0045_usermarketexchange_marketconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_cooldown_hours', models.PositiveIntegerField(default=864, help_text='Cooldown estándar (ej: 36 días = 864h)')),
                ('black_cooldown_hours', models.PositiveIntegerField(default=864, help_text='Cooldown mercado black')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketconfig',
            name='exchange_duration_hours',
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='is_black',
            field=models.BooleanField(default=False, help_text='¿Pertenece al mercado Black / BlackGOLD?'),
        ),
        migrations.AlterField(
            model_name='marketconfig',
            name='gold_multiplier',
            field=models.DecimalField(decimal_places=2, help_text='Relación: 1 unidad de mineral = X Gold (Cosmos o Black)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketconfig',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_configs', to='game.mineral'),
        ),
        migrations.CreateModel(
            name='UserMarketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('black_cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
