# Generated by Django 4.2.13 on 2026-03-31 03:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_marketglobalsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='black_gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
