# Generated by Django 4.2.13 on 2026-03-31 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_profile_black_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='black_market_discount',
            field=models.PositiveIntegerField(default=0, help_text='Descuento en % (0-100) para el Mercado Negro', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='chest',
            name='is_black_market',
            field=models.BooleanField(default=False, verbose_name='¿Aparece en Mercado Negro?'),
        ),
    ]
