# Generated by Django 4.2.13 on 2026-04-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0048_chest_black_market_discount_chest_is_black_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='required_miners',
            field=models.PositiveIntegerField(default=0, help_text='Mineros totales necesarios en inventario'),
        ),
        migrations.AddField(
            model_name='planet',
            name='required_tools',
            field=models.PositiveIntegerField(default=0, help_text='Herramientas totales necesarias en inventario'),
        ),
        migrations.AddField(
            model_name='planet',
            name='required_transports',
            field=models.PositiveIntegerField(default=0, help_text='Transportes totales necesarios en inventario'),
        ),
    ]
